### ISSUE TITLE
Turn on jwt validation for host-api

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/cattle#141]
Currently the stats api on the hosts is running unauthenticated.  We need to turn on authentication and validation of the jwt.  When the host-api binary is started `-auth true` and `-key Config.jwt_public_key_file()` should be passed to it.  (Those might not be the right flag names).  The host-api is started in the host_api.py in the python-agent.

**Comment by ibuildthecloud** [comment]
@pranavs18 When you fix this issue please write a validation test that grabs the url and token and then connects with a websocket from python.  Then validate that the some url does not work with no token or a bad token.

**Comment by pranavs18** [comment]
Sure. @ibuildthecloud  could you point me to the file which contains this part of the code ?

**Comment by ibuildthecloud** [comment]
Ideally this will just be a change in the python-agent and I already mentioned the host_api.py.  If need to debug the host-api or change it, the authentication logic is in https://github.com/rancherio/host-api/blob/master/auth/auth.go

**Comment by pranavs18** [comment]
Alright. Thanks, I'll look into it.

**Comment by pranavs18** [comment]
I had one question about the following lines of code which i figured out in the config.go , file - 

flag.BoolVar(&Config.Auth, "auth", false, "Authenticate requests")
flag.StringVar(&Config.Key, "public-key", "", "Public Key for Authentication")

What i was curious to know is that what is this public-key for ? and what purpose does this have and how is it different from the jwt token we are trying to pass?

**Comment by ibuildthecloud** [comment]
The jwt token has a signature on it.  The key is used to validate the signature.

**Comment by pranavs18** [comment]
So, @ibuildthecloud , I pass the two new arguments to the host_api process but in order to debug that, I tried putting some log statements and restarted the rancher-agent, but those log statements did not reflect on running the docker logs rancher-agent command. I believe, the logs should show the values for the Config.jwt_public_key_file() when the agent restarts. 

Secondly, in order to actually write a test for this, I  think, I need to import the websocket module for python and create a connection by passing the url. But when you talk about grabbing the url and the token, could you please elaborate on that?

**Comment by pranavs18** [comment]
ok, so i got the arguments passed in successfully after restarting the agent and after checking the logs , i see this - Launched ['host-api', '-cadvisor-url', 'http://127.0.0.1:9344', '-logtostderr=true', '-ip', '0.0.0.0', '-port', '9345', '-auth=true', '-key', '/var/lib/cattle/etc/cattle/api.crt'] as pid 786 .

In order to write the test for this, I'll grab this URL ( http://127.0.0.1:9344) and the key (/var/lib/cattle/etc/cattle/api.crt )and make assertions for both ? And also write a negative test to ensure this URL without the key doesn't get authorized ?

**Comment by pranavs18** [comment]
PR here - https://github.com/rancherio/python-agent/pull/45

**Comment by pranavs18** [comment]
For writing the test, I was trying to do something like this, but thinking about how do i pass in the public key. Do I just append it to the URL ?  - 

```
import os
import websocket
from cattle import Config


def test_host_api():
    url = "ws://0.0.0.0:9345"
    public_key = Config.jwt_public_key_file()
    websocket.create_connection(url, 60)
```

**Comment by pranavs18** [comment]
@ibuildthecloud  , I debugged this issue for quite a while and it seems, the server side code for host-api needs an additional logic for having a GO  Upgrader which upgrades the connection from HTTP to the websocket protocol.

func Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header, readBufSize, writeBufSize int) (*Conn, error)

Further, the external library you used parses "access-token" , so the query parameter will in the request needs to be changed to "access-token" from "token". 
I would need to use an external library like "github.com/gorilla/websocket" to handle upgradation of the connection.

**Comment by ibuildthecloud** [comment]
The go code should accept "token" so don't change cattle but instead make the go code work with "token."   I don't understand the other issue you describe regarding upgrade.  The current code is already a websocket and does the upgrade.
