### ISSUE TITLE
Projects do not send resource change events on update

### ISSUE THREAD

**Issue by vincent99** [rancherio/cattle#218]
Changes do not fire into the /v1/subscribe websocket when a project is created and goes through the transitioning states.

**Comment by sidharthamani** [comment]
@ibuildthecloud - How do I make it fire change events on state change?

**Comment by ibuildthecloud** [comment]
This a complicated one.  Events are fired in the backend when stuff changes, and then they are correlated to an account and resource.change events per account are fired.  The back end can not correlate a change on the project to an account that is listening because that relationship information is held in github.

What needs to change is that for projects we publish to a generic resource change event but then on the front end we filter according to the correct authorization.  So all account will subscribe to the project.changed firehouse.  This is all easier said than done.  Here's how i think it could be done.

1. In addition to resource.change, the UI subscribes to project.change

2. In https://github.com/rancherio/cattle/blob/e8f6206a13a4a8590ec0d9e2a71ac17ade896b04/code/framework/api-pub-sub/src/main/java/io/cattle/platform/api/pubsub/manager/SubscribeManager.java#L49 we need to add a setting of event names that will not be "qualified".  If a user subscribes to "foo", the qualified event becomes "foo;account=42".  We need the subscription to not be account specific.

3. A io.cattle.platform.api.pubsub.subscribe.ApiPubSubEventPostProcessor need to be able to communicate back to the caller that the event should be dropped, not just modified

4. A ApiPubSubEventPostProcessor should be created that looks for project.change events and filters them according to the token.  This is difficult though.  These processor are not ran as part of the API request so that do not have access to the HttpServletRequest.  The github token should be copied from the HttpServletRequest and put into the ApiRequest object.  The ApiPubSubEventPostProcessor does have access to the ApiRequest (but the encapsulated HttpServletRequest is invalid, don't use it).

5. An event listener should listen on resource.change events and then if the resource is a project, publish it to project.changed event.

@vincent99 So, you can see this isn't straight forward.  So how bad would the hack be on your side knowing that you don't get events for projects.

**Comment by vincent99** [comment]
@ibuildthecloud I can put in polling get to update the status on transitioning projects, which would work around the immediate problem on create/edit.  This seems like the most reasonable option.

(I don't really like that there's a special case for how just this particular kind of resource is updated.. but I can reuse this as a general fail-safe for all types so that if a resource.change message is lost it will eventually fix itself, which I was planning to do anyway.)

There will be other related problems, like if I create or rename a project owned by a team we both have access to.  It won't show up in your browser (like all other kinds of resources do), you'll have to refresh the page.  So we'd have to call that acceptable, or add worse hacks like polling all of /v1/projects every n seconds.

**Comment by vincent99** [comment]
Closing, the UI will poll for these.
